# based on https://github.com/PySlurm/pyslurm/blob/master/.travis.yml
sudo: required
language: julia
env:
  - SLURM=19.05.0

jobs:
  include:
    - stage: "Test"
      services:
        - docker
      before_install:
        - docker pull giovtorres/docker-centos7-slurm:$SLURM
        - docker run -d -it -h ernie -v $TRAVIS_BUILD_DIR:/ClusterManagers -v $TRAVIS_HOME/julia:/julia --name slurm-$SLURM giovtorres/docker-centos7-slurm:$SLURM
      install: true
      before_script:
        - docker exec slurm-$SLURM /julia/bin/julia --project=/ClusterManagers -e 'using Pkg; Pkg.build(verbose=true)'
      script:
        - docker exec slurm-$SLURM sbatch /ClusterManagers/test/slurm/simple_test.slurm
        - /julia/bin/julia --project=/ClusterManagers -e 'using Pkg; Pkg.test()'